name: Android CI

on:
  push:
    branches: [ main, deployment ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    #- name: Setup JDK
    #  uses: actions/setup-java@v2
    #  with:
    #    java-version: '11'
    #    distribution: 'adopt'
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    #- name: Build with Gradle
    #  run: ./gradlew clean build assembleDebug
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}

